/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/copymeal`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/feed`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/goals`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/lifestyle`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/metrics`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/preferences`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/summary`; params?: Router.UnknownInputParams; } | { pathname: `/meal/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/copymeal`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/feed`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/goals`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/lifestyle`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/metrics`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/preferences`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/summary`; params?: Router.UnknownOutputParams; } | { pathname: `/meal/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/copymeal${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/feed${`?${string}` | `#${string}` | ''}` | `/onboarding/goals${`?${string}` | `#${string}` | ''}` | `/onboarding/welcome${`?${string}` | `#${string}` | ''}` | `/onboarding/lifestyle${`?${string}` | `#${string}` | ''}` | `/onboarding/metrics${`?${string}` | `#${string}` | ''}` | `/onboarding/preferences${`?${string}` | `#${string}` | ''}` | `/onboarding/summary${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/copymeal`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/feed`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/goals`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/lifestyle`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/metrics`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/preferences`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/summary`; params?: Router.UnknownInputParams; } | `/meal/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/meal/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
